name: Build XivStrat App
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'macos-latest'
        type: choice
        options:
          - 'windows-latest'
          - 'macos-latest'
          - 'ubuntu-24.04'
      icon:
        description: 'Icon, Image URL, Optional'
        required: false
      width:
        description: 'Width, Optional'
        required: false
        default: '1200'
      height:
        description: 'Height, Optional'
        required: false
        default: '780'
      fullscreen:
        description: 'Fullscreen, At startup, Optional'
        required: false
        type: boolean
        default: false
      hide_title_bar:
        description: 'Hide TitleBar, MacOS only, Optional'
        required: false
        type: boolean
        default: false
      multi_arch:
        description: 'MultiArch, MacOS only, Optional'
        required: false
        type: boolean
        default: false
      targets:
        description: 'Targets, Linux only, Optional'
        required: false
        default: 'deb'
        type: choice
        options:
          - 'deb'
          - 'appimage'
          - 'rpm'

jobs:
  build:
    name: ${{ inputs.platform }}
    runs-on: ${{ inputs.platform }}
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get XivStrat latest commit
        id: xivstrat-commit
        shell: bash
        run: |
          COMMIT_SHA=$(git ls-remote https://github.com/mogworks/xivstrat.git com | cut -f1)
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "XivStrat latest commit: $COMMIT_SHA"

      - name: Cache XivStrat source code
        uses: actions/cache@v3
        id: cache-xivstrat-source
        with:
          path: xivstrat
          key: xivstrat-source-${{ steps.xivstrat-commit.outputs.sha }}
          restore-keys: |
            xivstrat-source-

      - name: Checkout XivStrat project
        if: steps.cache-xivstrat-source.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: mogworks/xivstrat
          ref: com
          path: xivstrat

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('xivstrat/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache XivStrat node_modules
        uses: actions/cache@v3
        id: cache-xivstrat-deps
        with:
          path: xivstrat/node_modules
          key: ${{ runner.os }}-xivstrat-deps-${{ hashFiles('xivstrat/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-xivstrat-deps-

      - name: Install Rust for ubuntu-24.04
        if: inputs.platform == 'ubuntu-24.04'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Install Rust for windows-latest
        if: inputs.platform == 'windows-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-msvc
          target: x86_64-pc-windows-msvc

      - name: Install Rust for macos-latest
        if: inputs.platform == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Install dependencies (ubuntu only)
        if: inputs.platform == 'ubuntu-24.04'
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libsoup3.0-dev libdbus-1-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev gnome-video-effects gnome-video-effects-extra
          version: 1.1

      - name: Install XivStrat dependencies  
        if: steps.cache-xivstrat-deps.outputs.cache-hit != 'true'
        working-directory: ./xivstrat
        run: pnpm install

      - name: Cache XivStrat build
        uses: actions/cache@v3
        id: cache-xivstrat-build
        with:
          path: xivstrat/dist
          key: ${{ runner.os }}-xivstrat-build-${{ steps.xivstrat-commit.outputs.sha }}-${{ hashFiles('xivstrat/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-xivstrat-build-${{ steps.xivstrat-commit.outputs.sha }}-
            ${{ runner.os }}-xivstrat-build-

      - name: Build XivStrat
        if: steps.cache-xivstrat-build.outputs.cache-hit != 'true'
        working-directory: ./xivstrat
        run: pnpm build

      - name: Install pake-cli local
        shell: bash
        run: |
          echo "install pake on local"
          npm install pake-cli

      - name: Rust cache restore
        uses: actions/cache/restore@v3
        id: cache_store
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            node_modules/pake-cli/src-tauri/target/
          key: ${{ inputs.platform }}-cargo-${{ hashFiles('node_modules/pake-cli/src-tauri/Cargo.lock') }}

      - name: Install dependencies
        shell: bash
        run: |
          npm install shelljs
          npm install axios

      - name: Build XivStrat with pake-cli
        shell: bash
        run: |
          node ./script/build_with_pake_cli.js
        env:
          URL: 'xivstrat/dist/index.html'
          LOCAL: true
          NAME: 'XivStrat'
          ICON: ${{ inputs.icon }}
          HEIGHT: ${{ inputs.height }}
          WIDTH: ${{ inputs.width }}
          HIDE_TITLE_BAR: ${{ inputs.hide_title_bar }}
          FULLSCREEN: ${{ inputs.fullscreen }}
          MULTI_ARCH: ${{ inputs.multi_arch }}
          TARGETS: ${{ inputs.targets }}
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
          PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: xivstrat-${{ inputs.platform }}.zip
          path: node_modules/pake-cli/output/*
          retention-days: 3

      - name: Rust cache store
        uses: actions/cache/save@v3
        if: steps.cache_store.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            node_modules/pake-cli/src-tauri/target/
          key: ${{ inputs.platform }}-cargo-${{ hashFiles('node_modules/pake-cli/src-tauri/Cargo.lock') }} 
